// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"fmt"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	// Message HTTP error message
	Message string `json:"message"`
}

// HistoryPoint defines model for HistoryPoint.
type HistoryPoint struct {
	Timestamp time.Time `json:"timestamp"`
	Value     float64   `json:"value"`
}

// Rate defines model for Rate.
type Rate struct {
	Currency  string         `json:"currency"`
	History   []HistoryPoint `json:"history"`
	Provider  string         `json:"provider"`
	Quote     string         `json:"quote"`
	Timestamp time.Time      `json:"timestamp"`
	Value     float64        `json:"value"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/rates)
	GetAllRates(c *fiber.Ctx) error

	// (GET /api/v1/rates/{code})
	GetRateByCurrency(c *fiber.Ctx, code string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetAllRates operation middleware
func (siw *ServerInterfaceWrapper) GetAllRates(c *fiber.Ctx) error {

	return siw.Handler.GetAllRates(c)
}

// GetRateByCurrency operation middleware
func (siw *ServerInterfaceWrapper) GetRateByCurrency(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", c.Params("code"), &code, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	return siw.Handler.GetRateByCurrency(c, code)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/v1/rates", wrapper.GetAllRates)

	router.Get(options.BaseURL+"/api/v1/rates/:code", wrapper.GetRateByCurrency)

}
